// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/registry.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Registry with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Registry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Registry with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegistryMultiError, or nil
// if none found.
func (m *Registry) ValidateAll() error {
	return m.validate(true)
}

func (m *Registry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Type

	// no validation rules for Url

	// no validation rules for Insecure

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegistryValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegistryValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegistryValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegistryValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegistryValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegistryValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch v := m.Credential.(type) {
	case *Registry_Basic:
		if v == nil {
			err := RegistryValidationError{
				field:  "Credential",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBasic()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RegistryValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RegistryValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBasic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RegistryValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return RegistryMultiError(errors)
	}

	return nil
}

// RegistryMultiError is an error wrapping multiple validation errors returned
// by Registry.ValidateAll() if the designated constraints aren't met.
type RegistryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegistryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegistryMultiError) AllErrors() []error { return m }

// RegistryValidationError is the validation error returned by
// Registry.Validate if the designated constraints aren't met.
type RegistryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegistryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegistryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegistryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegistryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegistryValidationError) ErrorName() string { return "RegistryValidationError" }

// Error satisfies the builtin error interface
func (e RegistryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegistry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegistryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegistryValidationError{}

// Validate checks the field values on RegistryBasicCredential with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegistryBasicCredential) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegistryBasicCredential with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegistryBasicCredentialMultiError, or nil if none found.
func (m *RegistryBasicCredential) ValidateAll() error {
	return m.validate(true)
}

func (m *RegistryBasicCredential) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Password

	if len(errors) > 0 {
		return RegistryBasicCredentialMultiError(errors)
	}

	return nil
}

// RegistryBasicCredentialMultiError is an error wrapping multiple validation
// errors returned by RegistryBasicCredential.ValidateAll() if the designated
// constraints aren't met.
type RegistryBasicCredentialMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegistryBasicCredentialMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegistryBasicCredentialMultiError) AllErrors() []error { return m }

// RegistryBasicCredentialValidationError is the validation error returned by
// RegistryBasicCredential.Validate if the designated constraints aren't met.
type RegistryBasicCredentialValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegistryBasicCredentialValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegistryBasicCredentialValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegistryBasicCredentialValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegistryBasicCredentialValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegistryBasicCredentialValidationError) ErrorName() string {
	return "RegistryBasicCredentialValidationError"
}

// Error satisfies the builtin error interface
func (e RegistryBasicCredentialValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegistryBasicCredential.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegistryBasicCredentialValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegistryBasicCredentialValidationError{}

// Validate checks the field values on ListRegistriesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRegistriesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRegistriesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRegistriesRequestMultiError, or nil if none found.
func (m *ListRegistriesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRegistriesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Search

	if len(errors) > 0 {
		return ListRegistriesRequestMultiError(errors)
	}

	return nil
}

// ListRegistriesRequestMultiError is an error wrapping multiple validation
// errors returned by ListRegistriesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRegistriesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRegistriesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRegistriesRequestMultiError) AllErrors() []error { return m }

// ListRegistriesRequestValidationError is the validation error returned by
// ListRegistriesRequest.Validate if the designated constraints aren't met.
type ListRegistriesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRegistriesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRegistriesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRegistriesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRegistriesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRegistriesRequestValidationError) ErrorName() string {
	return "ListRegistriesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRegistriesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRegistriesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRegistriesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRegistriesRequestValidationError{}

// Validate checks the field values on ListRegistriesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRegistriesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRegistriesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRegistriesResponseMultiError, or nil if none found.
func (m *ListRegistriesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRegistriesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRegistries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRegistriesResponseValidationError{
						field:  fmt.Sprintf("Registries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRegistriesResponseValidationError{
						field:  fmt.Sprintf("Registries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRegistriesResponseValidationError{
					field:  fmt.Sprintf("Registries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListRegistriesResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListRegistriesResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListRegistriesResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListRegistriesResponseMultiError(errors)
	}

	return nil
}

// ListRegistriesResponseMultiError is an error wrapping multiple validation
// errors returned by ListRegistriesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRegistriesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRegistriesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRegistriesResponseMultiError) AllErrors() []error { return m }

// ListRegistriesResponseValidationError is the validation error returned by
// ListRegistriesResponse.Validate if the designated constraints aren't met.
type ListRegistriesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRegistriesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRegistriesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRegistriesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRegistriesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRegistriesResponseValidationError) ErrorName() string {
	return "ListRegistriesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRegistriesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRegistriesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRegistriesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRegistriesResponseValidationError{}

// Validate checks the field values on GetRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRegistryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRegistryRequestMultiError, or nil if none found.
func (m *GetRegistryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRegistryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetRegistryRequestMultiError(errors)
	}

	return nil
}

// GetRegistryRequestMultiError is an error wrapping multiple validation errors
// returned by GetRegistryRequest.ValidateAll() if the designated constraints
// aren't met.
type GetRegistryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRegistryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRegistryRequestMultiError) AllErrors() []error { return m }

// GetRegistryRequestValidationError is the validation error returned by
// GetRegistryRequest.Validate if the designated constraints aren't met.
type GetRegistryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRegistryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRegistryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRegistryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRegistryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRegistryRequestValidationError) ErrorName() string {
	return "GetRegistryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRegistryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRegistryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRegistryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRegistryRequestValidationError{}

// Validate checks the field values on GetRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRegistryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRegistryResponseMultiError, or nil if none found.
func (m *GetRegistryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRegistryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRegistry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRegistryResponseValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRegistryResponseValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRegistryResponseValidationError{
				field:  "Registry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRegistryResponseMultiError(errors)
	}

	return nil
}

// GetRegistryResponseMultiError is an error wrapping multiple validation
// errors returned by GetRegistryResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRegistryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRegistryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRegistryResponseMultiError) AllErrors() []error { return m }

// GetRegistryResponseValidationError is the validation error returned by
// GetRegistryResponse.Validate if the designated constraints aren't met.
type GetRegistryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRegistryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRegistryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRegistryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRegistryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRegistryResponseValidationError) ErrorName() string {
	return "GetRegistryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRegistryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRegistryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRegistryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRegistryResponseValidationError{}

// Validate checks the field values on CreateRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRegistryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRegistryRequestMultiError, or nil if none found.
func (m *CreateRegistryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRegistryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Type

	// no validation rules for Url

	// no validation rules for Insecure

	switch v := m.Credential.(type) {
	case *CreateRegistryRequest_Basic:
		if v == nil {
			err := CreateRegistryRequestValidationError{
				field:  "Credential",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBasic()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateRegistryRequestValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateRegistryRequestValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBasic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateRegistryRequestValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return CreateRegistryRequestMultiError(errors)
	}

	return nil
}

// CreateRegistryRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRegistryRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRegistryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRegistryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRegistryRequestMultiError) AllErrors() []error { return m }

// CreateRegistryRequestValidationError is the validation error returned by
// CreateRegistryRequest.Validate if the designated constraints aren't met.
type CreateRegistryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRegistryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRegistryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRegistryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRegistryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRegistryRequestValidationError) ErrorName() string {
	return "CreateRegistryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRegistryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRegistryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRegistryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRegistryRequestValidationError{}

// Validate checks the field values on CreateRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRegistryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRegistryResponseMultiError, or nil if none found.
func (m *CreateRegistryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRegistryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRegistry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRegistryResponseValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRegistryResponseValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRegistryResponseValidationError{
				field:  "Registry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRegistryResponseMultiError(errors)
	}

	return nil
}

// CreateRegistryResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRegistryResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateRegistryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRegistryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRegistryResponseMultiError) AllErrors() []error { return m }

// CreateRegistryResponseValidationError is the validation error returned by
// CreateRegistryResponse.Validate if the designated constraints aren't met.
type CreateRegistryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRegistryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRegistryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRegistryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRegistryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRegistryResponseValidationError) ErrorName() string {
	return "CreateRegistryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRegistryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRegistryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRegistryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRegistryResponseValidationError{}

// Validate checks the field values on UpdateRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRegistryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRegistryRequestMultiError, or nil if none found.
func (m *UpdateRegistryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRegistryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Url

	// no validation rules for Insecure

	switch v := m.Credential.(type) {
	case *UpdateRegistryRequest_Basic:
		if v == nil {
			err := UpdateRegistryRequestValidationError{
				field:  "Credential",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBasic()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateRegistryRequestValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateRegistryRequestValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBasic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateRegistryRequestValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return UpdateRegistryRequestMultiError(errors)
	}

	return nil
}

// UpdateRegistryRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateRegistryRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateRegistryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRegistryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRegistryRequestMultiError) AllErrors() []error { return m }

// UpdateRegistryRequestValidationError is the validation error returned by
// UpdateRegistryRequest.Validate if the designated constraints aren't met.
type UpdateRegistryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRegistryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRegistryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRegistryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRegistryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRegistryRequestValidationError) ErrorName() string {
	return "UpdateRegistryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRegistryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRegistryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRegistryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRegistryRequestValidationError{}

// Validate checks the field values on UpdateRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRegistryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRegistryResponseMultiError, or nil if none found.
func (m *UpdateRegistryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRegistryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRegistry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRegistryResponseValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRegistryResponseValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRegistryResponseValidationError{
				field:  "Registry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateRegistryResponseMultiError(errors)
	}

	return nil
}

// UpdateRegistryResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateRegistryResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateRegistryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRegistryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRegistryResponseMultiError) AllErrors() []error { return m }

// UpdateRegistryResponseValidationError is the validation error returned by
// UpdateRegistryResponse.Validate if the designated constraints aren't met.
type UpdateRegistryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRegistryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRegistryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRegistryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRegistryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRegistryResponseValidationError) ErrorName() string {
	return "UpdateRegistryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRegistryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRegistryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRegistryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRegistryResponseValidationError{}

// Validate checks the field values on DeleteRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRegistryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRegistryRequestMultiError, or nil if none found.
func (m *DeleteRegistryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRegistryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteRegistryRequestMultiError(errors)
	}

	return nil
}

// DeleteRegistryRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteRegistryRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteRegistryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRegistryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRegistryRequestMultiError) AllErrors() []error { return m }

// DeleteRegistryRequestValidationError is the validation error returned by
// DeleteRegistryRequest.Validate if the designated constraints aren't met.
type DeleteRegistryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRegistryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRegistryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRegistryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRegistryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRegistryRequestValidationError) ErrorName() string {
	return "DeleteRegistryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRegistryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRegistryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRegistryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRegistryRequestValidationError{}

// Validate checks the field values on DeleteRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRegistryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRegistryResponseMultiError, or nil if none found.
func (m *DeleteRegistryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRegistryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteRegistryResponseMultiError(errors)
	}

	return nil
}

// DeleteRegistryResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteRegistryResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteRegistryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRegistryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRegistryResponseMultiError) AllErrors() []error { return m }

// DeleteRegistryResponseValidationError is the validation error returned by
// DeleteRegistryResponse.Validate if the designated constraints aren't met.
type DeleteRegistryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRegistryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRegistryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRegistryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRegistryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRegistryResponseValidationError) ErrorName() string {
	return "DeleteRegistryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRegistryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRegistryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRegistryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRegistryResponseValidationError{}

// Validate checks the field values on PingRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PingRegistryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingRegistryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PingRegistryRequestMultiError, or nil if none found.
func (m *PingRegistryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PingRegistryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Url

	// no validation rules for Insecure

	switch v := m.Credential.(type) {
	case *PingRegistryRequest_Basic:
		if v == nil {
			err := PingRegistryRequestValidationError{
				field:  "Credential",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBasic()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PingRegistryRequestValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PingRegistryRequestValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBasic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PingRegistryRequestValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return PingRegistryRequestMultiError(errors)
	}

	return nil
}

// PingRegistryRequestMultiError is an error wrapping multiple validation
// errors returned by PingRegistryRequest.ValidateAll() if the designated
// constraints aren't met.
type PingRegistryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingRegistryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingRegistryRequestMultiError) AllErrors() []error { return m }

// PingRegistryRequestValidationError is the validation error returned by
// PingRegistryRequest.Validate if the designated constraints aren't met.
type PingRegistryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingRegistryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingRegistryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingRegistryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingRegistryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingRegistryRequestValidationError) ErrorName() string {
	return "PingRegistryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PingRegistryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingRegistryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingRegistryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingRegistryRequestValidationError{}

// Validate checks the field values on PingRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PingRegistryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingRegistryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PingRegistryResponseMultiError, or nil if none found.
func (m *PingRegistryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PingRegistryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PingRegistryResponseMultiError(errors)
	}

	return nil
}

// PingRegistryResponseMultiError is an error wrapping multiple validation
// errors returned by PingRegistryResponse.ValidateAll() if the designated
// constraints aren't met.
type PingRegistryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingRegistryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingRegistryResponseMultiError) AllErrors() []error { return m }

// PingRegistryResponseValidationError is the validation error returned by
// PingRegistryResponse.Validate if the designated constraints aren't met.
type PingRegistryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingRegistryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingRegistryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingRegistryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingRegistryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingRegistryResponseValidationError) ErrorName() string {
	return "PingRegistryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PingRegistryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingRegistryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingRegistryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingRegistryResponseValidationError{}
