// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/registry.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registries_ListRegistries_FullMethodName = "/matrixhub.v1alpha1.Registries/ListRegistries"
	Registries_GetRegistry_FullMethodName    = "/matrixhub.v1alpha1.Registries/GetRegistry"
	Registries_CreateRegistry_FullMethodName = "/matrixhub.v1alpha1.Registries/CreateRegistry"
	Registries_UpdateRegistry_FullMethodName = "/matrixhub.v1alpha1.Registries/UpdateRegistry"
	Registries_DeleteRegistry_FullMethodName = "/matrixhub.v1alpha1.Registries/DeleteRegistry"
	Registries_PingRegistry_FullMethodName   = "/matrixhub.v1alpha1.Registries/PingRegistry"
)

// RegistriesClient is the client API for Registries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistriesClient interface {
	ListRegistries(ctx context.Context, in *ListRegistriesRequest, opts ...grpc.CallOption) (*ListRegistriesResponse, error)
	GetRegistry(ctx context.Context, in *GetRegistryRequest, opts ...grpc.CallOption) (*GetRegistryResponse, error)
	CreateRegistry(ctx context.Context, in *CreateRegistryRequest, opts ...grpc.CallOption) (*CreateRegistryResponse, error)
	UpdateRegistry(ctx context.Context, in *UpdateRegistryRequest, opts ...grpc.CallOption) (*UpdateRegistryResponse, error)
	DeleteRegistry(ctx context.Context, in *DeleteRegistryRequest, opts ...grpc.CallOption) (*DeleteRegistryResponse, error)
	PingRegistry(ctx context.Context, in *PingRegistryRequest, opts ...grpc.CallOption) (*PingRegistryResponse, error)
}

type registriesClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistriesClient(cc grpc.ClientConnInterface) RegistriesClient {
	return &registriesClient{cc}
}

func (c *registriesClient) ListRegistries(ctx context.Context, in *ListRegistriesRequest, opts ...grpc.CallOption) (*ListRegistriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegistriesResponse)
	err := c.cc.Invoke(ctx, Registries_ListRegistries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registriesClient) GetRegistry(ctx context.Context, in *GetRegistryRequest, opts ...grpc.CallOption) (*GetRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistryResponse)
	err := c.cc.Invoke(ctx, Registries_GetRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registriesClient) CreateRegistry(ctx context.Context, in *CreateRegistryRequest, opts ...grpc.CallOption) (*CreateRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRegistryResponse)
	err := c.cc.Invoke(ctx, Registries_CreateRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registriesClient) UpdateRegistry(ctx context.Context, in *UpdateRegistryRequest, opts ...grpc.CallOption) (*UpdateRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRegistryResponse)
	err := c.cc.Invoke(ctx, Registries_UpdateRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registriesClient) DeleteRegistry(ctx context.Context, in *DeleteRegistryRequest, opts ...grpc.CallOption) (*DeleteRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRegistryResponse)
	err := c.cc.Invoke(ctx, Registries_DeleteRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registriesClient) PingRegistry(ctx context.Context, in *PingRegistryRequest, opts ...grpc.CallOption) (*PingRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingRegistryResponse)
	err := c.cc.Invoke(ctx, Registries_PingRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistriesServer is the server API for Registries service.
// All implementations should embed UnimplementedRegistriesServer
// for forward compatibility.
type RegistriesServer interface {
	ListRegistries(context.Context, *ListRegistriesRequest) (*ListRegistriesResponse, error)
	GetRegistry(context.Context, *GetRegistryRequest) (*GetRegistryResponse, error)
	CreateRegistry(context.Context, *CreateRegistryRequest) (*CreateRegistryResponse, error)
	UpdateRegistry(context.Context, *UpdateRegistryRequest) (*UpdateRegistryResponse, error)
	DeleteRegistry(context.Context, *DeleteRegistryRequest) (*DeleteRegistryResponse, error)
	PingRegistry(context.Context, *PingRegistryRequest) (*PingRegistryResponse, error)
}

// UnimplementedRegistriesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistriesServer struct{}

func (UnimplementedRegistriesServer) ListRegistries(context.Context, *ListRegistriesRequest) (*ListRegistriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegistries not implemented")
}
func (UnimplementedRegistriesServer) GetRegistry(context.Context, *GetRegistryRequest) (*GetRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistry not implemented")
}
func (UnimplementedRegistriesServer) CreateRegistry(context.Context, *CreateRegistryRequest) (*CreateRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRegistry not implemented")
}
func (UnimplementedRegistriesServer) UpdateRegistry(context.Context, *UpdateRegistryRequest) (*UpdateRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRegistry not implemented")
}
func (UnimplementedRegistriesServer) DeleteRegistry(context.Context, *DeleteRegistryRequest) (*DeleteRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRegistry not implemented")
}
func (UnimplementedRegistriesServer) PingRegistry(context.Context, *PingRegistryRequest) (*PingRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PingRegistry not implemented")
}
func (UnimplementedRegistriesServer) testEmbeddedByValue() {}

// UnsafeRegistriesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistriesServer will
// result in compilation errors.
type UnsafeRegistriesServer interface {
	mustEmbedUnimplementedRegistriesServer()
}

func RegisterRegistriesServer(s grpc.ServiceRegistrar, srv RegistriesServer) {
	// If the following call panics, it indicates UnimplementedRegistriesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registries_ServiceDesc, srv)
}

func _Registries_ListRegistries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegistriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistriesServer).ListRegistries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registries_ListRegistries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistriesServer).ListRegistries(ctx, req.(*ListRegistriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registries_GetRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistriesServer).GetRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registries_GetRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistriesServer).GetRegistry(ctx, req.(*GetRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registries_CreateRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistriesServer).CreateRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registries_CreateRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistriesServer).CreateRegistry(ctx, req.(*CreateRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registries_UpdateRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistriesServer).UpdateRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registries_UpdateRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistriesServer).UpdateRegistry(ctx, req.(*UpdateRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registries_DeleteRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistriesServer).DeleteRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registries_DeleteRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistriesServer).DeleteRegistry(ctx, req.(*DeleteRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registries_PingRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistriesServer).PingRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registries_PingRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistriesServer).PingRegistry(ctx, req.(*PingRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registries_ServiceDesc is the grpc.ServiceDesc for Registries service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registries_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.Registries",
	HandlerType: (*RegistriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRegistries",
			Handler:    _Registries_ListRegistries_Handler,
		},
		{
			MethodName: "GetRegistry",
			Handler:    _Registries_GetRegistry_Handler,
		},
		{
			MethodName: "CreateRegistry",
			Handler:    _Registries_CreateRegistry_Handler,
		},
		{
			MethodName: "UpdateRegistry",
			Handler:    _Registries_UpdateRegistry_Handler,
		},
		{
			MethodName: "DeleteRegistry",
			Handler:    _Registries_DeleteRegistry_Handler,
		},
		{
			MethodName: "PingRegistry",
			Handler:    _Registries_PingRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/registry.proto",
}
